//
// Created by cervi on 02/10/2022.
//

#ifndef UNDERTALE_DEBUG_FLAGS_HPP
#define UNDERTALE_DEBUG_FLAGS_HPP

#define DEBUG_CUTSCENES
// #define DEBUG_SPRITES
// #define DEBUG_AUDIO

#endif //UNDERTALE_DEBUG_FLAGS_HPP
